# Generated by Django 3.0.9 on 2020-08-22 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20200822_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=10)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-order'],
            },
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-date_time']},
        ),
        migrations.AddField(
            model_name='club',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='place',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='logo_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Season'),
        ),
    ]
